[options.fish]
description = "Fish shell config."
links = [{ source = "config/fish", target = "~/.config/fish" }]
synced = false

[options.nvim]
description = "Neovim config."
links = [{ source = "config/nvim", target = "~/.config/nvim" }]
synced = false

[options.nvim-user]
description = "Neovim user custom config."
links = [
    { source = "config/nvim.user/lua", target = "~/.config/nvim/lua/user" },
]
depends = ["nvim"]
synced = false

[options.wezterm]
description = "Wezterm config."
links = [{ source = "config/wezterm", target = "~/.config/wezterm" }]
synced = false

[options.zsh]
description = "Zsh config."
links = [
    { source = "config/zsh", target = "~/.config/zsh" },
    { source = "config/zsh/.zshenv", target = "~/.zshenv" },
]
synced = false

[options.starship]
description = "Starship config."
links = [
    { source = "config/starship.toml", target = "~/.config/starship.toml" },
]
synced = false

[options.bash]
description = "Bash config."
links = [
    { source = "config/bash/.bash_profile", target = "~/.bash_profile" },
    { source = "config/bash/.bashrc", target = "~/.bashrc" },
]
synced = false

[options.git]
description = "Git config."
links = [{ source = "config/.gitconfig", target = "~/.gitconfig" }]
synced = false
