[options.bash]
group = "shell"
description = "Bash config."
links = [
    { source = "config/bash/.bash_profile", target = "~/.bash_profile" },
    { source = "config/bash/.bashrc", target = "~/.bashrc" },
]
synced = false

[options.fish]
group = "shell"
description = "Fish shell config."
links = [{ source = "config/fish", target = "~/.config/fish" }]
synced = false

[options.zsh]
group = "shell"
description = "Zsh config."
links = [
    { source = "config/zsh", target = "~/.config/zsh" },
    { source = "config/zsh/.zshenv", target = "~/.zshenv" },
]
synced = false

[options.starship]
group = "shell"
description = "Starship config."
links = [
    { source = "config/starship.toml", target = "~/.config/starship.toml" },
]
synced = false

[options.nvim]
group = "neovim"
description = "Neovim config."
links = [{ source = "config/nvim", target = "~/.config/nvim" }]
synced = false

[options.nvim-user]
group = "neovim"
description = "Neovim user custom config. (neovim)"
links = [
    { source = "config/nvim.user/lua", target = "~/.config/nvim/lua/user" },
]
dependencies = ["nvim"]
synced = false

[options.wezterm]
group = "terminal"
description = "Wezterm config."
links = [{ source = "config/wezterm", target = "~/.config/wezterm" }]
synced = false

[options.kitty]
group = "terminal"
description = "Kitty config."
links = [{ source = "config/kitty", target = "~/.config/kitty" }]
synced = false

[options.git]
description = "Git config."
links = [{ source = "config/.gitconfig", target = "~/.gitconfig" }]
synced = false
