#!/usr/bin/bash

export DOTFILES="${DOTFILES:-$HOME/.local/opt/dotfiles}"

# Define functions and conf.d directories
functions_dirs=("$DOTFILES/data/config/bash/functions" "$DOTFILES/data/user/bash/functions")
confd_dirs=("${confd_dirs[@]}" "$DOTFILES/data/config/bash/conf.d" "$DOTFILES/data/user/bash/conf.d")
if [[ $- == *i* ]]; then
  confd_dirs=("${confd_dirs[@]}" "$DOTFILES/data/config/bash/conf.d/interactive" "$DOTFILES/data/user/bash/conf.d/interactive")
fi
# Load the functions
for file in $("$DOTFILES/tools/bin/collectconf" "${functions_dirs[@]}"); do
  source "$file"
done
# Load the configuration
for file in $("$DOTFILES/tools/bin/collectconf" "${confd_dirs[@]}"); do
  source "$file"
done
unset functions_dirs
unset confd_dirs
