unlink ~/.local/bin/fakehome
# steam
unlink "$XDG_DATA_HOME/applications/steam.desktop"
unlink ~/.local/bin/steam
unlink ~/.local/bin/steam-runtime
# minecraft-launcher
unlink ~/.local/bin/minecraft-launcher
# hmcl-bin
unlink ~/.local/bin/hmcl-bin
# thunderbird
unlink ~/.local/bin/thunderbird
# firefox
unlink "$XDG_DATA_HOME/applications/firefox.desktop"
unlink ~/.local/bin/firefox
# code
unlink "$XDG_DATA_HOME/applications/code.desktop"
unlink "$XDG_DATA_HOME/applications/code-url-handler.desktop"
unlink ~/.local/bin/code
# jetbrains-fleet
unlink ~/.local/bin/jetbrains-fleet
