#!/usr/bin/bash

[[ $- != *i* ]] && return

export DOTFILES="${DOTFILES:-$HOME/.config/dotfiles}"
for file in $("$DOTFILES/utils/loadconf.py" "$DOTFILES/config/bash/conf.interactive.d" "$DOTFILES/user/bash/conf.interactive.d"); do
  source "$file"
done
