#!/usr/bin/bash

export DOTFILES="${DOTFILES:-$HOME/.config/dotfiles}"

# Define functions and conf.d directories
# functions_dirs=("$DOTFILES/config/bash/functions" "$DOTFILES/user/bash/functions")
confd_dirs=("${CONFD_LIST[@]}" "$DOTFILES/config/bash/conf.d" "$DOTFILES/user/bash/conf.d")
if [[ $- == *i* ]]; then
  confd_dirs=("${confd_dirs[@]}" "$DOTFILES/config/bash/conf.d/interactive" "$DOTFILES/user/bash/conf.d/interactive")
fi
# Load the configuration
# for file in $(echo "${functions_dirs[@]}" | xargs "$DOTFILES/local/bin/collectconf"); do
#   source "$file"
# done
for file in $("$DOTFILES/local/bin/collectconf" "${confd_dirs[@]}"); do
  source "$file"
done
# unset functions_dirs
unset confd_dirs
