#!/usr/bin/bash

export DOTFILES="${DOTFILES:-$HOME/.config/dotfiles}"
for file in $("$DOTFILES/utils/loadconf.py" "$DOTFILES/config/bash/conf.login.d" "$DOTFILES/user/bash/conf.login.d"); do
  source "$file"
done
. "$DOTFILES/config/bash/bashrc"
