#!/usr/bin/bash

CONFIG_DIR="$DOTFILES/data/config/waybar"

CONFIG_FILES=("$CONFIG_DIR/current" "$CONFIG_DIR/config" "$CONFIG_DIR/style.css")

trap "killall waybar" EXIT

while true; do
    waybar &
    inotifywait -e create,modify "${CONFIG_FILES[@]}"
    killall waybar
done
