#!/usr/bin/zsh

export DOTFILES="${DOTFILES:-$HOME/.local/opt/dotfiles}"

confd_dirs=("$DOTFILES/data/config/zsh/conf.d/login" "$DOTFILES/data/user/zsh/conf.d/login")

# . "$DOTFILES/data/config/zsh/zshrc"
