#!/usr/bin/zsh

autoload -Uz compinit
compinit

export IS_LOGIN=1
export DOTFILES="${DOTFILES:-$HOME/.config/dotfiles}"
for file in $("$DOTFILES/utils/loadconf.py" "$DOTFILES/config/bash/functions" "$DOTFILES/user/bash/functions"); do
  source "$file"
done
for file in $("$DOTFILES/utils/loadconf.py" "$DOTFILES/config/zsh/conf.login.d" "$DOTFILES/user/zsh/conf.login.d"); do
  source "$file"
done
