#!/usr/bin/zsh

autoload -Uz compinit
compinit

export DOTFILES="${DOTFILES:-$HOME/.config/dotfiles}"
for file in $("$DOTFILES/utils/loadconf.py" "$DOTFILES/config/zsh/conf.login.d" "$DOTFILES/user/zsh/conf.login.d"); do
  source "$file"
done
