#!/usr/bin/bash

for dir in "$@"; do
    if [ -d "$dir" ]; then
        for file in "$dir"/*; do
            if [ -f "$file" ]; then
                echo "$file"
            fi
        done
    fi
done | sort -t / -k 1
