#!/usr/bin/bash

CONFIG_DIR="$HOME/.config/dotfiles/config/dunst"

CONFIG_FILES=("$CONFIG_DIR/dunstrc")

trap "killall dunst" EXIT

while true; do
    dunst &
    inotifywait -e create,modify "${CONFIG_FILES[@]}"
    killall dunst
done
