#!/usr/bin/bash

function enable_gaps() {
  hyprctl keyword general:gaps_in 4 4 4 4
  hyprctl keyword general:gaps_out 8 8 8 8
  hyprctl keyword decoration:rounding 8
  waybarswitchtheme default
}

function disable_gaps() {
  hyprctl keyword general:gaps_in 0 0 0 0
  hyprctl keyword general:gaps_out 0 0 0 0
  hyprctl keyword decoration:rounding 0
  waybarswitchtheme default-nogaps
}

# If $argv[1] is not empty and
if [[ -n "$1" ]]; then
  if [[ "$1" == "enable" ]]; then
    enable_gaps
  else
    disable_gaps
  fi
else
  if [[ $(hyprctl getoption general:gaps_in | head -n 1 | awk '{print $3}') == "0" ]]; then
    enable_gaps
  else
    disable_gaps
  fi
fi
