;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

; modified https://github.com/gh0stzk/dotfiles

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = colors.ini
include-file = modules.ini


[bar/mybar]

monitor-strict = false

override-redirect = false

bottom = false
fixed-center = true

width = 90%
height = 30
offset-x = 5%
offset-y = 1.25%

background = ${color.bg}
foreground = ${color.fg}

radius = 4.0

line-size = 2
line-color = ${color.blue}

border-size = 8px
border-color = ${color.bg}

padding = 1

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "Fira Code:size=11;2"
font-2 = "Noto Color Emoji"
; Chinese
font-3 = "Noto Sans CJK SC:size=11;2"
; Icons
font-1 = "Symbols Nerd Font Mono:size=11;2"
; dpi = 96

modules-left = powermenu blank separator blank bi bspwm bd
modules-center = date
modules-right = bi cpu_bar bd blank bi memory_bar bd blank bi pulseaudio bd blank bi network bd

spacing = 0
separator =
dim-value = 1.0

;;locale = es_MX.UTF-8

tray-position = right
tray-detached = false
tray-maxsize = 16
tray-background = ${color.bg}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =


[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
